project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "bsvars.org"
  favicon: bsvars.org.png
  sidebar:
    logo: bsvars.org.png
  navbar:
    right:
      - icon: github
        url:  https://github.com/bsvars
      - icon: envelope
        href: mailto:contact@bsvars.org

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



